### ISSUE TITLE
FFMPEG Arguments

### ISSUE THREAD

**Issue by killer069** [discordjs/voice#124]
**Is your feature request related to a problem? Please describe.**
ffmpeg requires args for reconnecting

**Describe the ideal solution**
Add some ffmpeg args in [here](https://github.com/discordjs/voice/blob/main/src/audio/TransformerGraph.ts)

```
-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5
```

**Describe alternatives you've considered**
No alternatives

**Additional context**
None

**Comment by amishshah** [comment]
I've decided against adding this to `@discordjs/voice` since it means I'd have to make a decision on behalf of other users on which reconnect options to enable, what time frames to specify for reconnection etc.

It is better for users to specify this themselves after making their own decisions on these parameters.
